/// Flutter icons WeatherIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WeatherIcons
///      fonts:
///       - asset: fonts/WeatherIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class WeatherIcons {
  WeatherIcons._();

  static const _kFontFam = 'WeatherIcons';
  static const String _kFontPkg = null;

  static const IconData cloud = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snow = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rainy = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snowy = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rainbow = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData night = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hot = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cold = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloudy = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloudy_day = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloudy_night = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData windy = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thunder = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData windy_2 = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tornado = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mist = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData umbrella = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sunset = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sunrise = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wind_vane = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rain = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData humidity = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wind_vane_2 = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eclipse = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static IconData getWeatherIcon(String icon) {
    switch (icon) {
      case '01d':
        return WeatherIcons.night;
      case '01n':
        return WeatherIcons.sun;
        break;
      case '02d':
        return WeatherIcons.cloudy_day;
      case '02n':
        return WeatherIcons.cloudy_night;
        break;
      case '03d':
      case '03n':
        return WeatherIcons.cloud;
        break;
      case '04d':
      case '04n':
        return WeatherIcons.cloudy;
        break;
      case '09d':
      case '09n':
        return WeatherIcons.rainy;
        break;
      case '10d':
      case '10n':
        return WeatherIcons.rain;
        break;
      case '11d':
      case '11n':
        return WeatherIcons.thunder;
        break;
      case '13d':
      case '13n':
        return WeatherIcons.snow;
        break;
      case '50d':
      case '50n':
        return WeatherIcons.mist;
        break;
      default:
        return WeatherIcons.sun;
    }
  }
}
